from typing import List, Optional
from pydantic import BaseModel, Field, field_validator


class OrderItemAction(BaseModel):
    product_id: str
    quantity: int = 1

    @field_validator("quantity", mode="before")
    @classmethod
    def sanitize_quantity(cls, v):
        try:
            return max(1, int(v))
        except (ValueError, TypeError):
            return 1


class GeminiActionResponse(BaseModel):
    message: str = Field(..., description="Conversational text to be sent directly to the customer on Discord.")
    payment_link: Optional[str] = Field(None, description="Payment link if generated by backend.")
    payment_required: bool = Field(False, description="True if customer has expressed clear intent to purchase.")
    payment_processed: bool = Field(False, description="True ONLY when backend confirms payment is verified.")
    payment_id: Optional[str] = Field(None, description="Verified payment reference.")
    items: List[OrderItemAction] = Field(default_factory=list, description="All items the customer intends to purchase.")
    product_id: Optional[str] = Field(None, description="Single product ID fallback.")
    quantity: Optional[int] = Field(None, description="Single item quantity fallback.")
    image_files: List[str] = Field(default_factory=list, description="List of local product image paths to show.")
    order_action: Optional[str] = Field(None, description="Backend business operation required.")
    customer_information_required: bool = Field(False, description="True if waiting for phone/address.")
    order_ready: bool = Field(False, description="True when paid and delivery details are gathered.")

    # AI Extraction fields for phone, address, and maps links
    extracted_phone: Optional[str] = Field(None, description="Mobile number if explicitly provided by user in this message.")
    extracted_address: Optional[str] = Field(None, description="Physical delivery address/location (e.g. city, tole, ward). NEVER chat phrases.")
    extracted_location_link: Optional[str] = Field(None, description="Google Maps URL if provided.")

    @field_validator("order_action", mode="before")
    @classmethod
    def normalize_order_action(cls, v):
        if not v or not isinstance(v, str):
            return None
        action = v.strip().lower()
        if action in ["create", "create_order", "create_payment", "order", "purchase", "buy"]:
            return "create_payment"
        if action in ["verify", "verify_payment", "check_payment"]:
            return "verify_payment"
        if action in ["request_customer_details", "customer_details", "details", "request_details"]:
            return "request_customer_details"
        if action in ["finalize", "finalize_order", "complete", "confirm"]:
            return "finalize_order"
        return None